---

name: Update package index JSON file
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout the upstream repository
        uses: actions/checkout@v2
        with:
          path: upstream
          repository: esp8266/esp8266.github.io

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Convert the original JSON to ours
        run: |
          bundle exec ruby convert.rb upstream/stable/package_esp8266com_index.json > stable/package_esp8266_freebsd_github_io_index.json

      - name: Setup git
        run: |
          git config user.name 'Github Actions (update.yml)'
          git config user.email '<>'

      - name: Commit change if any
        run: |
          git status
          git commit -m 'update index.json' -a
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
